// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYA7NCnEUElIVLy04lAHrJVBcf_iKQxAU',
    appId: '1:933239969841:web:f1b4f48db56624e4131d10',
    messagingSenderId: '933239969841',
    projectId: 'sampleprojects-6ff4c',
    authDomain: 'sampleprojects-6ff4c.firebaseapp.com',
    storageBucket: 'sampleprojects-6ff4c.appspot.com',
    measurementId: 'G-EHPD182Z2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_Gquwq2ywVfR1puoJCgIaaazv_ZjqNs',
    appId: '1:933239969841:android:047485a15f1e35a4131d10',
    messagingSenderId: '933239969841',
    projectId: 'sampleprojects-6ff4c',
    storageBucket: 'sampleprojects-6ff4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu5FWUrF0tQkK0jSvc7sH81z4oJJl2hNU',
    appId: '1:933239969841:ios:77b22a66cae40e4c131d10',
    messagingSenderId: '933239969841',
    projectId: 'sampleprojects-6ff4c',
    storageBucket: 'sampleprojects-6ff4c.appspot.com',
    iosBundleId: 'com.example.crmNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu5FWUrF0tQkK0jSvc7sH81z4oJJl2hNU',
    appId: '1:933239969841:ios:77b22a66cae40e4c131d10',
    messagingSenderId: '933239969841',
    projectId: 'sampleprojects-6ff4c',
    storageBucket: 'sampleprojects-6ff4c.appspot.com',
    iosBundleId: 'com.example.crmNew',
  );
}
